### PR TITLE
Allow opening context menu by right clicking when AI are selected

### PR DESCRIPTION
**Pull request by mharis001**
**When merged this pull request will:**
- Allow opening context menu by right clicking when waypoint placement would normally occur due to selected AI and/or waypoints
    - Enabled through "Override Waypoint Placement" setting (default: `false`)
    - Can use <kbd>SHIFT</kbd> key to still place waypoints when enabled
- Requires new `tvSelection` and `tvSetSelected` script commands available on dev branch

### CODE REVIEW

**Review by CreepPork — APPROVED** [review]

**Review by neilzar — CHANGES_REQUESTED** [review]
When the context menu is open with a unit or group selected and I right-click somewhere it will place a waypoint, I expected a new context menu to be opened or the current to be closed.

**Comment by neilzar** [comment]
The previously mentioned issue is also a thing without selecting anything. Right-clicking will randomly not open the context menu and move the camera around. I think this may be an issue with incorrectly detecting the right click.

**Comment by mharis001** [comment]
Can't reproduce. Moving the camera is intentional since the context menu should be opened if camera panning was started between RMB down and up events.

**Review by neilzar — APPROVED** [review]
I guess it is just down to the tiniest movement being detected between button-down and up.

**Pull request merged**
