### PR TITLE
Add various improvements to the inventory display

### LINKED ISSUE #490: Feature Request: Zeus Container Ammo Filter
**Is your feature request related to a problem?**
Before Zeus Enhanced (I'm not sure if Achilles/Ares added this), I could double click a weapon in a container and it would show me all the different compatible ammo mags, but with Zeus Enhanced it no longer does this, making it a huge headache to find what magazines are compatible with what guns, especially when mods are involved.

**Solution you'd like:**
Adding in a button or making it so double clicking a weapon shows up all compatible ammo/mags that can be added into the containers inventory.

**Alternatives you've considered:**
An addon option that restores the container UI back to the original non-ZEN UI.

**Additional context:**
I couldn't find an image/video of exactly what I'm asking, but for the alternative, I mean having an option to restore containers back this sort of UI
https://i.imgur.com/2zBlFm5.jpg

(Note: Commented this on the Steam page but noticed after that you guys do feature requests on GitHub)

### PR DESCRIPTION
**Pull request by mharis001**
**When merged this pull request will:**
- Add a "weapon specific items" mode, Close #490 
    - Can be accessed by clicking the weapon specific items button at the bottom or by double clicking a weapon in the list
    - Shows only items/magazines compatible with the selected weapon
    - Add common `isWeapon` function
- Add different sorting options to the items list
    - Can now be sorted by name or amount and in ascending or descending order
    - Add common `initListNBoxSorting` function
- Allow for items to be added 1, 5, 10, or 50 at a time using the <kbd>SHIFT</kbd> and <kbd>CTRL</kbd> keys
- Allow for items to be searched by class name using the `class ` prefix (like 3DEN asset browser search)
- Perform misc. code cleanup such as removing magic numbers on the `inventory` component

<details>
<summary>Images</summary>

inventory_1

inventory_2

</details>

### CODE REVIEW

**Comment by fire-391** [comment]
Can this also work with ACE's CSW? As it is now mortar rounds and ammo cans can only be added to an inventory by finding the class name and adding it via scripting in 3den. Or spawning one in with Zeus which creates a huge pile on the ground and loading them in by hand.

**Review by neilzar — COMMENTED** [review]
I would like to see the weapon editor expanded to create a weapon with attachments, so not placing all the items in the inventory separately. Can be achieved with the command 'addWeaponWithAttachmentsCargoGlobal'.

**Comment by Kexanone** [comment]
> I would like to see the weapon editor expanded to create a weapon with attachments, so not placing all the items in the inventory separately. Can be achieved with the command 'addWeaponWithAttachmentsCargoGlobal'.

If we want to provide a convoluted interface, we might as well add an import/export function to save the time spent to get the loadouts right, but this might be out of the scope for this particular PR. We can keep it as it is for now and add more features later on.

**Review by neilzar — APPROVED** [review]
> If we want to provide a convoluted interface, we might as well add an import/export function to save the time spent to get the loadouts right, but this might be out of the scope for this particular PR. We can keep it as it is for now and add more features later on.

Yea, I do agree it is out of scope a bit. I'll approve since I didn't find any issues.

**Comment by mharis001** [comment]
@fire-391 ACE CSW deals with vehicle weapons. The weapon specific items UI in this PR is meant to work with infantry weapons.

**Review by CreepPork — APPROVED** [review]

**Pull request merged**
