### PR TITLE
Add attach/detach keybinds and allow editing attached objects directly

### PR DESCRIPTION
**Pull request by mharis001**
**When merged this pull request will:**
- Add "Attach Objects" and "Detach Objects" keybinds to attach/detach multiple objects at a time
- Allow editing attached objects directly
    - Previously, attached objects would snap back to their original position when edited through Zeus
    - Now, we manually re-attach them based on their new relative position to the parent object
- Move all attached objects handling to new `attached_objects` component

### CODE REVIEW

**Comment by Kexanone** [comment]
Any reason you chose <kbd>Alt</kbd> over <kbd>Ctrl</kbd> for the default keybind?

**Review by Kexanone — APPROVED** [review]

**Comment by mharis001** [comment]
Do not remember why. Would <kbd>Ctrl</kbd> be a better default?

**Comment by Kexanone** [comment]
I messed up before... I meant to replace <kbd>Shift</kbd> with <kbd>Ctrl</kbd>, since I find <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Key</kbd> a more natural choice than <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Key</kbd>, but it's probably more a matter of personal preference.

**Comment by mharis001** [comment]
Changed to CTRL + SHIFT + _. Feels like the most natural to use.

**Comment by Kexanone** [comment]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd> is actually even better. Anyway ppl can adjust it to whatever they want anyway, so no big deal in the first place.

**Pull request merged**
