### PR TITLE
Add Advanced Rappelling compatibility

### PR DESCRIPTION
**Pull request by Kexanone**
**When merged this pull request will:**
- Add compatibility addon for using [Duda's Advanced Rappelling](https://github.com/sethduda/AdvancedRappelling) for fast-roping waypoint and reinforcements.
- Slightly refactor fastroping in main addon

### CODE REVIEW

**Comment by Kexanone** [comment]
To Do: Get reinforcements working

**Comment by mharis001** [comment]
Maybe these should be two separate waypoints (Fastrope and Advanced Rappel) because the mods could be run together. We could add conditions to waypoints so that they only show if the required mods are loaded.

**Comment by Kexanone** [comment]
Sounds like a good alternative approach. Would you propose the AR waypoint in a compat. or part of the main addon? If I remember correctly we decided against having anything but ACE as soft dependency, that's why I went the compat. route in the first place.

**Comment by mharis001** [comment]
Yeah, I think we can revisit that decision for some other big mods. I think both a new component (separation of features/responsibilities) or just in the `ai` component are good options. With waypoint conditions, this feature could be added without a hard dependency.

**Comment by mharis001** [comment]
I separated out the waypoints into "Fastrope" and "Rappel" and reworked how reinforcements handles the different insertion methods for air vehicles. I think we should keep the Advanced Rapelling compatibility as a separate optional component.

**Review by mharis001 — APPROVED** [review]

**Comment by mharis001** [comment]
@Kexanone, I think this is good to go. Please look over my changes and merge when ready.

**Comment by Kexanone** [comment]
Looks good to me, but still needs to be tested.

**Comment by mharis001** [comment]
I did the usual testing, and everything seemed okay. I think we are good to merge.

**Pull request merged**
